### ISSUE TITLE
Не перезагружается

### ISSUE THREAD

**Issue by varfomoleev** [developerivanov/SimpleRestart#1]
Здравствуйте, Дмитрий, играя на вашем сервере в 5:00 произошло отключение сервера без перезагрузки. 
(Мой часовой пояс +3 МСК.)
![Screenshot_20210814-083555_VTosters](https://user-images.githubusercontent.com/87407026/129432045-e9c8f71f-f436-4ce4-9d15-08d060b92a8c.jpg)

**Comment by developerivanov** [comment]
Спасибо. Исправил
